#!/usr/bin/env python3
"""Operational capacity and queueing model for centralized scheduler work."""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class WorkloadClass:
    """One scheduler operation class and its resource demand."""

    name: str
    arrival_rate_per_s: float
    cpu_ms_per_visit: float
    elapsed_ms_per_visit: float | None = None

    def __post_init__(self) -> None:
        if self.arrival_rate_per_s < 0:
            raise ValueError("arrival_rate_per_s must be nonnegative")
        if self.cpu_ms_per_visit < 0:
            raise ValueError("cpu_ms_per_visit must be nonnegative")
        if self.elapsed_ms_per_visit is not None and self.elapsed_ms_per_visit < 0:
            raise ValueError("elapsed_ms_per_visit must be nonnegative")

    @property
    def cpu_load_cores(self) -> float:
        """Average CPU-core demand from this class."""
        return self.arrival_rate_per_s * self.cpu_ms_per_visit / 1000.0

    @property
    def worker_occupancy(self) -> float:
        """Average occupied workers when elapsed service is available."""
        service_ms = (
            self.cpu_ms_per_visit
            if self.elapsed_ms_per_visit is None
            else self.elapsed_ms_per_visit
        )
        return self.arrival_rate_per_s * service_ms / 1000.0


@dataclass(frozen=True)
class CapacityLimits:
    """Task-rate limits at the scheduler's CPU and worker resources."""

    cpu_tasks_per_s: float
    worker_tasks_per_s: float

    @property
    def tasks_per_s(self) -> float:
        return min(self.cpu_tasks_per_s, self.worker_tasks_per_s)

    @property
    def bottleneck(self) -> str:
        if math.isclose(self.cpu_tasks_per_s, self.worker_tasks_per_s):
            return "joint"
        return (
            "cpu"
            if self.cpu_tasks_per_s < self.worker_tasks_per_s
            else "workers"
        )


def usl_relative_capacity(workers: int, contention: float, coherency: float) -> float:
    """Universal Scalability Law capacity relative to one worker."""
    if workers < 1:
        raise ValueError("workers must be at least one")
    if contention < 0 or coherency < 0:
        raise ValueError("USL parameters must be nonnegative")
    denominator = (
        1.0
        + contention * (workers - 1)
        + coherency * workers * (workers - 1)
    )
    return workers / denominator


def total_cpu_load(workloads: Iterable[WorkloadClass]) -> float:
    """Aggregate offered CPU load in core-equivalents."""
    return sum(workload.cpu_load_cores for workload in workloads)


def total_worker_occupancy(workloads: Iterable[WorkloadClass]) -> float:
    """Aggregate offered worker occupancy in worker-equivalents."""
    return sum(workload.worker_occupancy for workload in workloads)


def scheduler_utilization(
    workloads: Iterable[WorkloadClass], effective_cpu_cores: float
) -> float:
    """CPU utilization relative to the scheduler's effective capacity."""
    if effective_cpu_cores <= 0:
        raise ValueError("effective_cpu_cores must be positive")
    return total_cpu_load(workloads) / effective_cpu_cores


def worker_utilization(
    workloads: Iterable[WorkloadClass], effective_workers: float
) -> float:
    """Occupied-worker fraction relative to measured effective workers."""
    if effective_workers <= 0:
        raise ValueError("effective_workers must be positive")
    return total_worker_occupancy(workloads) / effective_workers


def background_poll_rate(idle_robots: float, poll_period_s: float) -> float:
    """Assignment-query rate generated by periodic idle-robot polling."""
    if idle_robots < 0:
        raise ValueError("idle_robots must be nonnegative")
    if poll_period_s <= 0:
        raise ValueError("poll_period_s must be positive")
    return idle_robots / poll_period_s


def task_capacity_after_background_load(
    *,
    effective_cpu_cores: float,
    background_cpu_load_cores: float,
    cpu_ms_per_task: float,
    utilization_limit: float = 1.0,
) -> float:
    """Task-rate capacity after non-task-proportional CPU load.

    The result is tasks/s.  A utilization limit below one is engineering
    headroom; mathematical stability uses a limit of one and a strict
    inequality.
    """
    if effective_cpu_cores <= 0:
        raise ValueError("effective_cpu_cores must be positive")
    if background_cpu_load_cores < 0:
        raise ValueError("background_cpu_load_cores must be nonnegative")
    if cpu_ms_per_task <= 0:
        raise ValueError("cpu_ms_per_task must be positive")
    if not 0 < utilization_limit <= 1:
        raise ValueError("utilization_limit must be in (0, 1]")
    available_cores = (
        utilization_limit * effective_cpu_cores - background_cpu_load_cores
    )
    return max(available_cores, 0.0) * 1000.0 / cpu_ms_per_task


def task_capacity_limits_after_background_load(
    *,
    effective_cpu_cores: float,
    effective_workers: float,
    background_workloads: Iterable[WorkloadClass],
    cpu_ms_per_task: float,
    elapsed_ms_per_task: float,
    utilization_limit: float = 1.0,
) -> CapacityLimits:
    """Compute CPU- and worker-limited task capacity separately.

    CPU demand and in-service elapsed occupancy are different resources.  The
    effective worker count should come from the execution model or a measured
    scaling curve; it is not assumed equal to the configured thread count.
    """
    if effective_cpu_cores <= 0:
        raise ValueError("effective_cpu_cores must be positive")
    if effective_workers <= 0:
        raise ValueError("effective_workers must be positive")
    if cpu_ms_per_task <= 0 or elapsed_ms_per_task <= 0:
        raise ValueError("task demands must be positive")
    if not 0 < utilization_limit <= 1:
        raise ValueError("utilization_limit must be in (0, 1]")

    background = tuple(background_workloads)
    available_cpu = max(
        utilization_limit * effective_cpu_cores - total_cpu_load(background),
        0.0,
    )
    available_workers = max(
        utilization_limit * effective_workers
        - total_worker_occupancy(background),
        0.0,
    )
    return CapacityLimits(
        cpu_tasks_per_s=available_cpu * 1000.0 / cpu_ms_per_task,
        worker_tasks_per_s=(
            available_workers * 1000.0 / elapsed_ms_per_task
        ),
    )


def erlang_c_wait_probability(
    arrival_rate_per_s: float, mean_service_s: float, servers: int
) -> float:
    """Probability that an arrival waits in an M/M/c queue."""
    if arrival_rate_per_s < 0:
        raise ValueError("arrival_rate_per_s must be nonnegative")
    if mean_service_s <= 0:
        raise ValueError("mean_service_s must be positive")
    if servers < 1:
        raise ValueError("servers must be at least one")
    offered_load = arrival_rate_per_s * mean_service_s
    utilization = offered_load / servers
    if utilization >= 1:
        return 1.0
    if offered_load == 0:
        return 0.0

    terms = [1.0]
    for index in range(1, servers):
        terms.append(terms[-1] * offered_load / index)
    final_term = terms[-1] * offered_load / servers / (1.0 - utilization)
    return final_term / (sum(terms) + final_term)


def allen_cunneen_mean_wait_s(
    *,
    arrival_rate_per_s: float,
    mean_service_s: float,
    servers: int,
    arrival_scv: float,
    service_scv: float,
) -> float:
    """Two-moment approximation for mean queue wait in a GI/G/c queue."""
    if arrival_scv < 0 or service_scv < 0:
        raise ValueError("squared coefficients of variation must be nonnegative")
    offered_load = arrival_rate_per_s * mean_service_s
    utilization = offered_load / servers
    if utilization >= 1:
        return math.inf
    if arrival_rate_per_s == 0:
        return 0.0

    probability_wait = erlang_c_wait_probability(
        arrival_rate_per_s, mean_service_s, servers
    )
    mmc_wait = (
        probability_wait
        * mean_service_s
        / (servers * (1.0 - utilization))
    )
    variability_factor = 0.5 * (arrival_scv + service_scv)
    return variability_factor * mmc_wait


def service_scv(samples_s: Iterable[float]) -> float:
    """Population squared coefficient of variation for service samples."""
    samples = tuple(float(sample) for sample in samples_s)
    if not samples:
        raise ValueError("at least one sample is required")
    if any(sample < 0 for sample in samples):
        raise ValueError("service samples must be nonnegative")
    mean = sum(samples) / len(samples)
    if mean == 0:
        return 0.0
    variance = sum((sample - mean) ** 2 for sample in samples) / len(samples)
    return variance / (mean * mean)
